<?php

namespace GateAdminBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRepository extends \Doctrine\ORM\EntityRepository
{
    
  public function getAllPosts($currentPage = 1)
{
    // Create our query
    $query = $this->createQueryBuilder('p')
        ->orderBy('p.vid', 'DESC')
        ->where('p.showveh = 0')  
        ->getQuery();

    // No need to manually get get the result ($query->getResult())

    $paginator = $this->paginate($query, $currentPage);

    return $paginator;
}

 public function getSpecificPosts($id ,$currentPage = 1)
{
   $query = $this->createQueryBuilder('v')
   
  
   ->where('v.did = :name')
   ->setParameter('name', $id)
     
    // Create our query
  
        ->getQuery();

    // No need to manually get get the result ($query->getResult())

    $paginator = $this->paginate($query, $currentPage);

    return $paginator;
}




public function paginate($dql, $page = 1, $limit = 5)
{
    $paginator = new Paginator($dql);

    $paginator->getQuery()
        ->setFirstResult($limit * ($page - 1)) // Offset
        ->setMaxResults($limit); // Limit

    return $paginator;
}   
    
    
}
